### PR TITLE
Server Address support hostname or IP address

### PR DESCRIPTION
**Pull request by s7lx**
Server Address support hostname or IP address

### CODE REVIEW

**Comment by aa65535** [comment]
not support hostname.

**Comment by zealic** [comment]
+1, I like that

**Comment by s7lx** [comment]
@aa65535 I am sure it works.

**Comment by s7lx** [comment]
@zealic edit /usr/lib/lua/luci/model/cbi/shadowsocks.lua  by yourself

**Comment by aa65535** [comment]
@s7lx shadowsocks/openwrt-shadowsocks#124

**Pull request closed without merging**
