### PR TITLE
Shadowsocks: Delete Check iptables-mod-tproxy

### PR DESCRIPTION
**Pull request by lrinQVQ**
iptables-mod-tproxy is remove in https://github.com/shadowsocks/openwrt-shadowsocks/commit/4989d9f3cfa23803cc36420d4ea40de65215cae3  so delete it!

### CODE REVIEW

**Comment by cokebar** [comment]
UDP-relay needs tproxy, so checking of tproxy is needed. If you have no tproxy installed, udp relay will be disabled. otherwise, udp-relay is enabled.

**Comment by lrinQVQ** [comment]
But if i don't install tproxy ,UDP-relay is work.

**Comment by lrinQVQ** [comment]
I use shadowsocks-libev-spec,build from https://github.com/shadowsocks/openwrt-shadowsocks
My Router is Xiaomi miwifi mini,If i check iptables-mod-tproxy ,udp relay  is "Unusable - Missing iptables-mod-tproxy",but if i don't check  iptables-mod-tproxy,and ss-redir,ss-rules work ,udp relay( ss-tunnel)work too.

**Comment by cokebar** [comment]
@lrinQVQ You misunderstood the udp-relay. 

ss-tunnel is a TCP/UDP tunnel. In luci-shadowsocks-libev-spec, "UDP Forward" use ss-tunnel, which do nothing with iptables and tpoxy. This function is often used to forward DNS requests. Actually, ss-tunnel can forward UDP DNS request as well as DNS request.

When you enable the function "UDP Relay Server", then tproxy is needed. This feature do nothing with ss-tunnel. It uses ss-redir, iptables and tproxy. It can make all(or specific ip range) udp traffic go through shadowsocks. This is useful for apps which uses udp, like online games.

**Comment by lrinQVQ** [comment]
@cokebar Thanks for your patience to answer,but i hava a question,please wait a few time

**Pull request closed without merging**
